import { useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { jsPDF } from "jspdf";
import {
  ArrowRight,
  BrainCircuit,
  CheckCircle2,
  Download,
  FileJson,
  FileText,
  FileType,
  Loader2,
} from "lucide-react";

import { useAnalysisStore } from "@/store/analysis.store";
import { useReviewStore } from "@/store/review.store";
import type { AnalysisResult } from "@/shared/types/analysis";

function generateMarkdown(result: AnalysisResult, reviewCount: number): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# SignalDesk AI Analysis Report

**Generated:** ${date}  
**Reviews Analyzed:** ${reviewCount}  
**Overall Severity:** ${result.severity}  
**Severity Score:** ${result.severityScore}/100

---

## Executive Summary

${result.executiveSummary}

---

## Top Issues

`;

  result.topIssues.forEach((issue, i) => {
    md += `### ${i + 1}. ${issue.title}

**Severity:** ${issue.severity}  
**Affected Users:** ${issue.affectedCount}

${issue.description}

**Root Cause:** ${issue.rootCause}  
**Recommended Fix:** ${issue.recommendedFix}

`;
  });

  md += `---

## Engineering Tickets

`;

  result.jiraTickets.forEach((ticket, i) => {
    md += `### SIGNAL-${String(i + 1).padStart(3, "0")}: ${ticket.title}

**Priority:** ${ticket.priority}

${ticket.description}

**Acceptance Criteria:**
${ticket.acceptanceCriteria.map((c) => `- [ ] ${c}`).join("\n")}

`;
  });

  md += `---

## Customer Communications

### Customer Email

\`\`\`
${result.customerEmail}
\`\`\`

### Status Page Update

\`\`\`
${result.statusPageUpdate}
\`\`\`

### Social Media Update

\`\`\`
${result.socialMediaUpdate}
\`\`\`

---

*Report generated by SignalDesk AI*
`;

  return md;
}

function generateJSON(result: AnalysisResult, reviewCount: number): string {
  const report = {
    meta: {
      generatedAt: new Date().toISOString(),
      reviewsAnalyzed: reviewCount,
      generator: "SignalDesk AI",
    },
    severity: {
      level: result.severity,
      score: result.severityScore,
    },
    executiveSummary: result.executiveSummary,
    topIssues: result.topIssues,
    jiraTickets: result.jiraTickets.map((t, i) => ({
      ...t,
      ticketId: `SIGNAL-${String(i + 1).padStart(3, "0")}`,
    })),
    communications: {
      customerEmail: result.customerEmail,
      statusPageUpdate: result.statusPageUpdate,
      socialMediaUpdate: result.socialMediaUpdate,
    },
  };

  return JSON.stringify(report, null, 2);
}

function generatePDF(result: AnalysisResult, reviewCount: number): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Colors
  const colors = {
    primary: [59, 130, 246] as [number, number, number],
    purple: [139, 92, 246] as [number, number, number],
    dark: [10, 15, 28] as [number, number, number],
    gray: [100, 116, 139] as [number, number, number],
    white: [255, 255, 255] as [number, number, number],
    critical: [239, 68, 68] as [number, number, number],
    high: [249, 115, 22] as [number, number, number],
    medium: [245, 158, 11] as [number, number, number],
    low: [16, 185, 129] as [number, number, number],
  };

  const severityColor = (severity: string): [number, number, number] => {
    switch (severity) {
      case "Critical": return colors.critical;
      case "High": return colors.high;
      case "Medium": return colors.medium;
      default: return colors.low;
    }
  };

  const addText = (text: string, fontSize: number, isBold = false, color = colors.dark) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    
    lines.forEach((line: string) => {
      if (y > pageHeight - 30) {
        doc.addPage();
        y = 30;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.45;
    });
    y += 3;
  };

  const addSection = (title: string) => {
    if (y > pageHeight - 60) {
      doc.addPage();
      y = 30;
    }
    y += 10;
    
    // Section divider line
    doc.setDrawColor(...colors.primary);
    doc.setLineWidth(0.5);
    doc.line(margin, y - 6, margin + 40, y - 6);
    
    addText(title, 16, true, colors.dark);
    y += 4;
  };

  // ==========================================
  // COVER PAGE - Premium Header
  // ==========================================
  
  // Dark header background with gradient effect
  doc.setFillColor(...colors.dark);
  doc.rect(0, 0, pageWidth, 70, "F");
  
  // Gradient accent line
  doc.setFillColor(...colors.primary);
  doc.rect(0, 70, pageWidth, 3, "F");
  
  // Logo area
  doc.setTextColor(...colors.white);
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text("SignalDesk", margin, 30);
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 180, 220);
  doc.text("AI Crisis Intelligence Report", margin, 42);
  
  // Date and metadata
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(10);
  doc.setTextColor(150, 160, 180);
  doc.text(date, pageWidth - margin - doc.getTextWidth(date), 42);
  doc.text(`${reviewCount} Reviews Analyzed`, pageWidth - margin - doc.getTextWidth(`${reviewCount} Reviews Analyzed`), 52);
  
  y = 90;

  // ==========================================
  // KEY METRICS CARDS
  // ==========================================
  
  const cardWidth = (contentWidth - 20) / 3;
  const cardHeight = 45;
  const cardY = y;
  
  // Card 1: Reviews Analyzed
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, cardY, cardWidth, cardHeight, 4, 4, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, cardY, cardWidth, cardHeight, 4, 4, "S");
  
  doc.setFontSize(9);
  doc.setTextColor(...colors.gray);
  doc.text("REVIEWS ANALYZED", margin + 10, cardY + 15);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.dark);
  doc.text(String(reviewCount), margin + 10, cardY + 35);
  
  // Card 2: Severity Level
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin + cardWidth + 10, cardY, cardWidth, cardHeight, 4, 4, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin + cardWidth + 10, cardY, cardWidth, cardHeight, 4, 4, "S");
  
  doc.setFontSize(9);
  doc.setTextColor(...colors.gray);
  doc.text("SEVERITY LEVEL", margin + cardWidth + 20, cardY + 15);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...severityColor(result.severity));
  doc.text(result.severity, margin + cardWidth + 20, cardY + 35);
  
  // Card 3: Severity Score
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin + (cardWidth + 10) * 2, cardY, cardWidth, cardHeight, 4, 4, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin + (cardWidth + 10) * 2, cardY, cardWidth, cardHeight, 4, 4, "S");
  
  doc.setFontSize(9);
  doc.setTextColor(...colors.gray);
  doc.text("SEVERITY SCORE", margin + (cardWidth + 10) * 2 + 10, cardY + 15);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.dark);
  doc.text(`${result.severityScore}/100`, margin + (cardWidth + 10) * 2 + 10, cardY + 35);
  
  // Progress bar for severity score
  const progressY = cardY + 40;
  const progressWidth = cardWidth - 20;
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(margin + (cardWidth + 10) * 2 + 10, progressY, progressWidth, 3, 1, 1, "F");
  doc.setFillColor(...severityColor(result.severity));
  doc.roundedRect(margin + (cardWidth + 10) * 2 + 10, progressY, progressWidth * (result.severityScore / 100), 3, 1, 1, "F");
  
  y = cardY + cardHeight + 20;

  // ==========================================
  // SEVERITY DISTRIBUTION CHART
  // ==========================================
  
  const severityCounts = {
    Critical: result.topIssues.filter(i => i.severity === "Critical").length,
    High: result.topIssues.filter(i => i.severity === "High").length,
    Medium: result.topIssues.filter(i => i.severity === "Medium").length,
    Low: result.topIssues.filter(i => i.severity === "Low").length,
  };
  
  // Chart title
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.dark);
  doc.text("Issue Distribution", margin, y);
  y += 15;
  
  // Horizontal bar chart
  const maxCount = Math.max(...Object.values(severityCounts), 1);
  const barHeight = 12;
  const barMaxWidth = 100;
  
  Object.entries(severityCounts).forEach(([severity, count]) => {
    // Label
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...colors.gray);
    doc.text(severity, margin, y + 8);
    
    // Bar background
    doc.setFillColor(240, 240, 245);
    doc.roundedRect(margin + 35, y, barMaxWidth, barHeight, 2, 2, "F");
    
    // Bar fill
    const barWidth = (count / maxCount) * barMaxWidth;
    if (barWidth > 0) {
      doc.setFillColor(...severityColor(severity));
      doc.roundedRect(margin + 35, y, barWidth, barHeight, 2, 2, "F");
    }
    
    // Count
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.dark);
    doc.text(String(count), margin + 35 + barMaxWidth + 10, y + 8);
    
    y += barHeight + 5;
  });
  
  y += 10;

  // ==========================================
  // EXECUTIVE SUMMARY
  // ==========================================
  
  addSection("Executive Summary");
  
  // Quote styling with left border
  doc.setDrawColor(...colors.primary);
  doc.setLineWidth(2);
  doc.line(margin, y - 2, margin, y + 40);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  const summaryLines = doc.splitTextToSize(result.executiveSummary, contentWidth - 10);
  summaryLines.forEach((line: string) => {
    if (y > pageHeight - 30) {
      doc.addPage();
      y = 30;
    }
    doc.text(line, margin + 8, y);
    y += 5;
  });
  y += 10;

  // ==========================================
  // TOP ISSUES
  // ==========================================
  
  addSection("Top Issues");
  
  result.topIssues.forEach((issue, i) => {
    if (y > pageHeight - 70) {
      doc.addPage();
      y = 30;
    }
    
    // Issue card background
    doc.setFillColor(250, 251, 252);
    doc.roundedRect(margin, y - 3, contentWidth, 50, 3, 3, "F");
    
    // Severity indicator bar
    doc.setFillColor(...severityColor(issue.severity));
    doc.rect(margin, y - 3, 3, 50, "F");
    
    // Issue number and title
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.dark);
    doc.text(`${i + 1}. ${issue.title}`, margin + 10, y + 8);
    
    // Severity badge
    const badgeX = pageWidth - margin - 40;
    doc.setFillColor(...severityColor(issue.severity));
    doc.roundedRect(badgeX, y, 35, 14, 3, 3, "F");
    doc.setFontSize(8);
    doc.setTextColor(...colors.white);
    const badgeText = issue.severity.toUpperCase();
    doc.text(badgeText, badgeX + 17.5 - doc.getTextWidth(badgeText) / 2, y + 9);
    
    // Affected count
    doc.setFontSize(9);
    doc.setTextColor(...colors.gray);
    doc.text(`${issue.affectedCount} users affected`, margin + 10, y + 18);
    
// Description (render each wrapped line separately instead of rejoining them)
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    const descLines: string[] = doc.splitTextToSize(issue.description, contentWidth - 25);
    let descY = y + 28;
    descLines.slice(0, 2).forEach((line: string) => {
      doc.text(line, margin + 10, descY);
      descY += 4.5;
    });
    
    // Root cause (wrap properly instead of hard character-truncating)
    if (issue.rootCause) {
      doc.setFontSize(8);
      doc.setTextColor(...colors.gray);
      const rootCauseLines: string[] = doc.splitTextToSize(`Root cause: ${issue.rootCause}`, contentWidth - 25);
      doc.text(rootCauseLines[0] + (rootCauseLines.length > 1 ? "..." : ""), margin + 10, descY + 4);
    }
    
    y += 58;
  });

  // ==========================================
  // ENGINEERING TICKETS
  // ==========================================
  
  doc.addPage();
  y = 30;
  addSection("Engineering Tickets");
  
  result.jiraTickets.forEach((ticket, i) => {
    if (y > pageHeight - 60) {
      doc.addPage();
      y = 30;
    }
    
    // Ticket ID
    doc.setFillColor(...colors.primary);
    doc.roundedRect(margin, y - 3, 70, 16, 3, 3, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.white);
    doc.text(`SIGNAL-${String(i + 1).padStart(3, "0")}`, margin + 8, y + 7);
    
    // Priority badge
    const priorityColor = ticket.priority === "Critical" ? colors.critical :
                          ticket.priority === "High" ? colors.high :
                          ticket.priority === "Medium" ? colors.medium : colors.low;
    doc.setFillColor(...priorityColor);
    doc.roundedRect(margin + 75, y - 3, 45, 16, 3, 3, "F");
    doc.setFontSize(8);
    doc.text(ticket.priority.toUpperCase(), margin + 80, y + 7);
    
    y += 18;
    
    // Title
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...colors.dark);
    doc.text(ticket.title, margin, y);
    y += 8;
    
    // Description
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(75, 85, 99);
    const ticketDesc = doc.splitTextToSize(ticket.description, contentWidth);
    ticketDesc.slice(0, 3).forEach((line: string) => {
      doc.text(line, margin, y);
      y += 4;
    });
    
    // Acceptance criteria
    y += 4;
    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text("Acceptance Criteria:", margin, y);
    y += 5;
    ticket.acceptanceCriteria.slice(0, 3).forEach((criteria) => {
      doc.setFillColor(226, 232, 240);
      doc.circle(margin + 3, y - 1.5, 1.5, "F");
      doc.text(criteria.substring(0, 80), margin + 8, y);
      y += 5;
    });
    
    y += 10;
  });

  // ==========================================
  // CUSTOMER COMMUNICATIONS
  // ==========================================
  
  doc.addPage();
  y = 30;
  addSection("Customer Communications");
  
  // Email
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.dark);
  doc.text("Customer Email Template", margin, y);
  y += 8;
  
  const emailLines: string[] = doc.splitTextToSize(result.customerEmail, contentWidth - 16);
  const emailLinesShown = emailLines.slice(0, 8);
  const emailBoxHeight = emailLinesShown.length * 4.5 + 14;
  
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y - 3, contentWidth, emailBoxHeight, 3, 3, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y - 3, contentWidth, emailBoxHeight, 3, 3, "S");
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  emailLinesShown.forEach((line: string) => {
    doc.text(line, margin + 8, y + 5);
    y += 4.5;
  });
  y += 15;
  
  // Status Page
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.dark);
  doc.text("Status Page Update", margin, y);
  y += 8;
  
  const statusLines: string[] = doc.splitTextToSize(result.statusPageUpdate, contentWidth - 16);
  const statusLinesShown = statusLines.slice(0, 5);
  const statusBoxHeight = statusLinesShown.length * 4.5 + 14;
  
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y - 3, contentWidth, statusBoxHeight, 3, 3, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y - 3, contentWidth, statusBoxHeight, 3, 3, "S");
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  statusLinesShown.forEach((line: string) => {
    doc.text(line, margin + 8, y + 5);
    y += 4.5;
  });
  y += 15;
  
  // Social Media
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...colors.dark);
  doc.text("Social Media Response", margin, y);
  y += 8;
  
  const socialLines: string[] = doc.splitTextToSize(result.socialMediaUpdate, contentWidth - 16);
  const socialLinesShown = socialLines.slice(0, 4);
  const socialBoxHeight = socialLinesShown.length * 4.5 + 14;
  
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y - 3, contentWidth, socialBoxHeight, 3, 3, "F");
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y - 3, contentWidth, socialBoxHeight, 3, 3, "S");
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 65, 81);
  socialLinesShown.forEach((line: string) => {
    doc.text(line, margin + 8, y + 5);
    y += 4.5;
  });

  // ==========================================
  // FOOTER ON ALL PAGES
  // ==========================================
  
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
    
    // Footer text
    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text(
      `SignalDesk AI • Crisis Intelligence Report`,
      margin,
      pageHeight - 8
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin - 25,
      pageHeight - 8
    );
  }

  return doc;
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export default function Reports() {
  const { result } = useAnalysisStore();
  const { items } = useReviewStore();
  const [exporting, setExporting] = useState<string | null>(null);

  const reviewCount = items.length;

  async function handleExportMarkdown() {
    if (!result) return;
    setExporting("markdown");
    try {
      const md = generateMarkdown(result, reviewCount);
      downloadFile(md, "signaldesk-report.md", "text/markdown");
      toast.success("Markdown report downloaded");
    } finally {
      setExporting(null);
    }
  }

  async function handleExportJSON() {
    if (!result) return;
    setExporting("json");
    try {
      const json = generateJSON(result, reviewCount);
      downloadFile(json, "signaldesk-report.json", "application/json");
      toast.success("JSON report downloaded");
    } finally {
      setExporting(null);
    }
  }

  async function handleExportPDF() {
    if (!result) return;
    setExporting("pdf");
    try {
      const doc = generatePDF(result, reviewCount);
      doc.save("signaldesk-report.pdf");
      toast.success("PDF report downloaded");
    } finally {
      setExporting(null);
    }
  }

  // Empty state - no analysis yet
  if (!result) {
    return (
      <div className="space-y-10" data-testid="reports-empty">
        <div>
          <h1 className="text-3xl font-bold text-white">Reports</h1>
          <p className="mt-2 text-slate-400">Export analysis results in multiple formats.</p>
        </div>

        <div className="flex flex-col items-center justify-center rounded-2xl border border-white/[0.08] bg-gradient-to-br from-slate-900/80 to-slate-900/40 backdrop-blur-xl py-20">
          <div className="rounded-2xl bg-gradient-to-br from-indigo-500/20 to-purple-500/10 p-6 border border-indigo-500/20">
            <FileText size={40} className="text-indigo-400" />
          </div>
          <h2 className="mt-8 text-2xl font-bold text-white">No Analysis to Export</h2>
          <p className="mt-3 max-w-md text-center text-slate-400">
            Run AI analysis first to generate reports. You'll be able to export
            executive summaries, Jira tickets, and customer communications.
          </p>
          <Link
            to="/analysis"
            data-testid="go-to-analysis-btn"
            className="mt-8 flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 px-6 py-3 font-semibold text-white shadow-lg shadow-indigo-500/25 transition-all hover:shadow-xl"
          >
            <BrainCircuit size={20} />
            Go to Analysis
            <ArrowRight size={18} />
          </Link>
        </div>
      </div>
    );
  }

  // Has analysis - show export options
  return (
    <div className="space-y-10" data-testid="reports-ready">
      <div>
        <h1 className="text-3xl font-bold text-white">Reports</h1>
        <p className="mt-2 text-slate-400">Export analysis results in multiple formats.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <div className="group rounded-2xl border border-white/[0.08] bg-gradient-to-br from-slate-900/80 to-slate-900/40 backdrop-blur-xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-500/5 hover:border-white/[0.12]">
          <div className="flex items-center gap-4">
            <div className="rounded-xl bg-gradient-to-br from-blue-500/20 to-blue-600/10 border border-blue-500/20 p-3">
              <FileType size={24} className="text-blue-400" />
            </div>
            <div>
              <h3 className="font-semibold text-white">Markdown</h3>
              <p className="text-sm text-slate-500">For documentation</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-slate-400">
            Export as formatted Markdown for wikis, Notion, or GitHub.
          </p>
          <button
            onClick={handleExportMarkdown}
            disabled={exporting !== null}
            data-testid="export-markdown-btn"
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border border-white/[0.1] bg-white/[0.02] py-2.5 font-medium text-slate-300 transition-all hover:bg-white/[0.06] disabled:opacity-50"
          >
            {exporting === "markdown" ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Export .md
          </button>
        </div>

        <div className="group rounded-2xl border border-white/[0.08] bg-gradient-to-br from-slate-900/80 to-slate-900/40 backdrop-blur-xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-amber-500/5 hover:border-white/[0.12]">
          <div className="flex items-center gap-4">
            <div className="rounded-xl bg-gradient-to-br from-amber-500/20 to-amber-600/10 border border-amber-500/20 p-3">
              <FileJson size={24} className="text-amber-400" />
            </div>
            <div>
              <h3 className="font-semibold text-white">JSON</h3>
              <p className="text-sm text-slate-500">For integrations</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-slate-400">
            Export structured data for APIs, automation, or further processing.
          </p>
          <button
            onClick={handleExportJSON}
            disabled={exporting !== null}
            data-testid="export-json-btn"
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border border-white/[0.1] bg-white/[0.02] py-2.5 font-medium text-slate-300 transition-all hover:bg-white/[0.06] disabled:opacity-50"
          >
            {exporting === "json" ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Export .json
          </button>
        </div>

        <div className="group rounded-2xl border border-white/[0.08] bg-gradient-to-br from-slate-900/80 to-slate-900/40 backdrop-blur-xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-red-500/5 hover:border-white/[0.12]">
          <div className="flex items-center gap-4">
            <div className="rounded-xl bg-gradient-to-br from-red-500/20 to-red-600/10 border border-red-500/20 p-3">
              <FileText size={24} className="text-red-400" />
            </div>
            <div>
              <h3 className="font-semibold text-white">PDF</h3>
              <p className="text-sm text-slate-500">For stakeholders</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-slate-400">
            Professional report for executives, meetings, and presentations.
          </p>
          <button
            onClick={handleExportPDF}
            disabled={exporting !== null}
            data-testid="export-pdf-btn"
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border border-white/[0.1] bg-white/[0.02] py-2.5 font-medium text-slate-300 transition-all hover:bg-white/[0.06] disabled:opacity-50"
          >
            {exporting === "pdf" ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Export .pdf
          </button>
        </div>
      </div>

      {/* Summary of what will be exported */}
      <div className="rounded-2xl border border-white/[0.08] bg-gradient-to-br from-slate-900/80 to-slate-900/40 backdrop-blur-xl p-6">
        <h3 className="font-semibold text-white">Export Contents</h3>
        <div className="mt-4 grid gap-3 text-sm md:grid-cols-2 lg:grid-cols-4">
          <div className="flex items-center gap-2 text-slate-300">
            <CheckCircle2 size={16} className="text-emerald-400" />
            Executive Summary
          </div>
          <div className="flex items-center gap-2 text-slate-300">
            <CheckCircle2 size={16} className="text-emerald-400" />
            {result.topIssues.length} Top Issues
          </div>
          <div className="flex items-center gap-2 text-slate-300">
            <CheckCircle2 size={16} className="text-emerald-400" />
            {result.jiraTickets.length} Jira Tickets
          </div>
          <div className="flex items-center gap-2 text-slate-300">
            <CheckCircle2 size={16} className="text-emerald-400" />
            Customer Communications
          </div>
        </div>
      </div>

      {/* Quick navigation */}
      <div className="flex items-center justify-between rounded-2xl border border-emerald-500/20 bg-gradient-to-r from-emerald-950/30 to-cyan-950/20 p-6">
        <div>
          <h3 className="font-semibold text-white">All done!</h3>
          <p className="text-sm text-slate-400">
            Your analysis is complete. Export reports or return to Dashboard.
          </p>
        </div>
        <Link
          to="/dashboard"
          className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-emerald-600 to-cyan-600 px-5 py-2.5 font-medium text-white shadow-lg shadow-emerald-500/20 transition-all hover:shadow-xl"
        >
          Back to Dashboard
          <ArrowRight size={16} />
        </Link>
      </div>
    </div>
  );
}
