import { useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { jsPDF } from "jspdf";
import {
  ArrowRight,
  BrainCircuit,
  CheckCircle2,
  Download,
  FileJson,
  FileText,
  FileType,
  Loader2,
} from "lucide-react";

import PageHeader from "@/shared/components/PageHeader";
import { useAnalysisStore } from "@/store/analysis.store";
import { useReviewStore } from "@/store/review.store";
import type { AnalysisResult } from "@/shared/types/analysis";

function generateMarkdown(result: AnalysisResult, reviewCount: number): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# SignalDesk AI Analysis Report

**Generated:** ${date}  
**Reviews Analyzed:** ${reviewCount}  
**Overall Severity:** ${result.severity}  
**Severity Score:** ${result.severityScore}/100

---

## Executive Summary

${result.executiveSummary}

---

## Top Issues

`;

  result.topIssues.forEach((issue, i) => {
    md += `### ${i + 1}. ${issue.title}

**Severity:** ${issue.severity}  
**Affected Users:** ${issue.affectedCount}

${issue.description}

**Root Cause:** ${issue.rootCause}  
**Recommended Fix:** ${issue.recommendedFix}

`;
  });

  md += `---

## Engineering Tickets

`;

  result.jiraTickets.forEach((ticket, i) => {
    md += `### SIGNAL-${String(i + 1).padStart(3, "0")}: ${ticket.title}

**Priority:** ${ticket.priority}

${ticket.description}

**Acceptance Criteria:**
${ticket.acceptanceCriteria.map((c) => `- [ ] ${c}`).join("\n")}

`;
  });

  md += `---

## Customer Communications

### Customer Email

\`\`\`
${result.customerEmail}
\`\`\`

### Status Page Update

\`\`\`
${result.statusPageUpdate}
\`\`\`

### Social Media Update

\`\`\`
${result.socialMediaUpdate}
\`\`\`

---

*Report generated by SignalDesk AI*
`;

  return md;
}

function generateJSON(result: AnalysisResult, reviewCount: number): string {
  const report = {
    meta: {
      generatedAt: new Date().toISOString(),
      reviewsAnalyzed: reviewCount,
      generator: "SignalDesk AI",
    },
    severity: {
      level: result.severity,
      score: result.severityScore,
    },
    executiveSummary: result.executiveSummary,
    topIssues: result.topIssues,
    jiraTickets: result.jiraTickets.map((t, i) => ({
      ...t,
      ticketId: `SIGNAL-${String(i + 1).padStart(3, "0")}`,
    })),
    communications: {
      customerEmail: result.customerEmail,
      statusPageUpdate: result.statusPageUpdate,
      socialMediaUpdate: result.socialMediaUpdate,
    },
  };

  return JSON.stringify(report, null, 2);
}

function generatePDF(result: AnalysisResult, reviewCount: number): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, fontSize: number, isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, contentWidth);
    
    lines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.5;
    });
    y += 4;
  };

  const addSection = (title: string) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    y += 8;
    doc.setDrawColor(200);
    doc.line(margin, y - 4, pageWidth - margin, y - 4);
    addText(title, 14, true);
    y += 2;
  };

  // Header
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, 45, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("SignalDesk AI", margin, 20);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Crisis Intelligence Report", margin, 30);
  
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(date, pageWidth - margin - doc.getTextWidth(date), 30);
  
  doc.setTextColor(0, 0, 0);
  y = 60;

  // Key Metrics
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(margin, y - 5, contentWidth, 30, 3, 3, "F");
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);
  doc.text("REVIEWS ANALYZED", margin + 10, y + 5);
  doc.text("SEVERITY LEVEL", margin + 60, y + 5);
  doc.text("SEVERITY SCORE", margin + 110, y + 5);
  
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text(String(reviewCount), margin + 10, y + 18);
  doc.text(result.severity, margin + 60, y + 18);
  doc.text(`${result.severityScore}/100`, margin + 110, y + 18);
  
  y = 100;

  // Executive Summary
  addSection("Executive Summary");
  doc.setTextColor(55, 65, 81);
  addText(result.executiveSummary, 11);

  // Top Issues
  addSection("Top Issues");
  result.topIssues.forEach((issue, i) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    
    doc.setTextColor(0, 0, 0);
    addText(`${i + 1}. ${issue.title}`, 12, true);
    
    doc.setTextColor(107, 114, 128);
    doc.setFontSize(10);
    doc.text(`Severity: ${issue.severity} | Affected: ${issue.affectedCount}`, margin, y);
    y += 6;
    
    doc.setTextColor(55, 65, 81);
    addText(issue.description, 10);
    
    doc.setTextColor(107, 114, 128);
    addText(`Root Cause: ${issue.rootCause}`, 9);
    addText(`Fix: ${issue.recommendedFix}`, 9);
    y += 4;
  });

  // Jira Tickets
  addSection("Engineering Tickets");
  result.jiraTickets.forEach((ticket, i) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    
    doc.setTextColor(0, 0, 0);
    addText(`SIGNAL-${String(i + 1).padStart(3, "0")}: ${ticket.title}`, 11, true);
    
    doc.setTextColor(107, 114, 128);
    doc.setFontSize(9);
    doc.text(`Priority: ${ticket.priority}`, margin, y);
    y += 5;
    
    doc.setTextColor(55, 65, 81);
    addText(ticket.description, 10);
    y += 2;
  });

  // Customer Communications
  addSection("Customer Communications");
  
  doc.setTextColor(0, 0, 0);
  addText("Customer Email", 11, true);
  doc.setTextColor(55, 65, 81);
  addText(result.customerEmail, 9);
  y += 4;
  
  doc.setTextColor(0, 0, 0);
  addText("Status Page Update", 11, true);
  doc.setTextColor(55, 65, 81);
  addText(result.statusPageUpdate, 9);
  y += 4;
  
  doc.setTextColor(0, 0, 0);
  addText("Social Media Update", 11, true);
  doc.setTextColor(55, 65, 81);
  addText(result.socialMediaUpdate, 9);

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by SignalDesk AI`,
      pageWidth / 2,
      290,
      { align: "center" }
    );
  }

  return doc;
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export default function Reports() {
  const { result } = useAnalysisStore();
  const { items } = useReviewStore();
  const [exporting, setExporting] = useState<string | null>(null);

  const reviewCount = items.length;

  async function handleExportMarkdown() {
    if (!result) return;
    setExporting("markdown");
    try {
      const md = generateMarkdown(result, reviewCount);
      downloadFile(md, "signaldesk-report.md", "text/markdown");
      toast.success("Markdown report downloaded");
    } finally {
      setExporting(null);
    }
  }

  async function handleExportJSON() {
    if (!result) return;
    setExporting("json");
    try {
      const json = generateJSON(result, reviewCount);
      downloadFile(json, "signaldesk-report.json", "application/json");
      toast.success("JSON report downloaded");
    } finally {
      setExporting(null);
    }
  }

  async function handleExportPDF() {
    if (!result) return;
    setExporting("pdf");
    try {
      const doc = generatePDF(result, reviewCount);
      doc.save("signaldesk-report.pdf");
      toast.success("PDF report downloaded");
    } finally {
      setExporting(null);
    }
  }

  // Empty state - no analysis yet
  if (!result) {
    return (
      <div className="space-y-10" data-testid="reports-empty">
        <PageHeader
          title="Reports"
          description="Export analysis results in multiple formats."
        />

        <div className="flex flex-col items-center justify-center rounded-3xl border border-dashed py-20">
          <div className="rounded-full bg-primary/10 p-6">
            <FileText size={40} className="text-primary" />
          </div>
          <h2 className="mt-8 text-2xl font-bold">No Analysis to Export</h2>
          <p className="mt-3 max-w-md text-center text-muted-foreground">
            Run AI analysis first to generate reports. You'll be able to export
            executive summaries, Jira tickets, and customer communications.
          </p>
          <Link
            to="/analysis"
            data-testid="go-to-analysis-btn"
            className="mt-8 flex items-center gap-2 rounded-2xl bg-primary px-6 py-3 font-semibold text-primary-foreground transition-all hover:scale-[1.02] hover:shadow-lg"
          >
            <BrainCircuit size={20} />
            Go to Analysis
            <ArrowRight size={18} />
          </Link>
        </div>
      </div>
    );
  }

  // Has analysis - show export options
  return (
    <div className="space-y-10" data-testid="reports-ready">
      <PageHeader
        title="Reports"
        description="Export analysis results in multiple formats."
      />

      <div className="grid gap-6 md:grid-cols-3">
        <div className="group rounded-2xl border bg-card p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
          <div className="flex items-center gap-4">
            <div className="rounded-xl bg-blue-500/10 p-3">
              <FileType size={24} className="text-blue-500" />
            </div>
            <div>
              <h3 className="font-semibold">Markdown</h3>
              <p className="text-sm text-muted-foreground">For documentation</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">
            Export as formatted Markdown for wikis, Notion, or GitHub.
          </p>
          <button
            onClick={handleExportMarkdown}
            disabled={exporting !== null}
            data-testid="export-markdown-btn"
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border py-2.5 font-medium transition-colors hover:bg-accent disabled:opacity-50"
          >
            {exporting === "markdown" ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Export .md
          </button>
        </div>

        <div className="group rounded-2xl border bg-card p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
          <div className="flex items-center gap-4">
            <div className="rounded-xl bg-amber-500/10 p-3">
              <FileJson size={24} className="text-amber-500" />
            </div>
            <div>
              <h3 className="font-semibold">JSON</h3>
              <p className="text-sm text-muted-foreground">For integrations</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">
            Export structured data for APIs, automation, or further processing.
          </p>
          <button
            onClick={handleExportJSON}
            disabled={exporting !== null}
            data-testid="export-json-btn"
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border py-2.5 font-medium transition-colors hover:bg-accent disabled:opacity-50"
          >
            {exporting === "json" ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Export .json
          </button>
        </div>

        <div className="group rounded-2xl border bg-card p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
          <div className="flex items-center gap-4">
            <div className="rounded-xl bg-red-500/10 p-3">
              <FileText size={24} className="text-red-500" />
            </div>
            <div>
              <h3 className="font-semibold">PDF</h3>
              <p className="text-sm text-muted-foreground">For stakeholders</p>
            </div>
          </div>
          <p className="mt-4 text-sm text-muted-foreground">
            Professional report for executives, meetings, and presentations.
          </p>
          <button
            onClick={handleExportPDF}
            disabled={exporting !== null}
            data-testid="export-pdf-btn"
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border py-2.5 font-medium transition-colors hover:bg-accent disabled:opacity-50"
          >
            {exporting === "pdf" ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Export .pdf
          </button>
        </div>
      </div>

      {/* Summary of what will be exported */}
      <div className="rounded-2xl border bg-card p-6">
        <h3 className="font-semibold">Export Contents</h3>
        <div className="mt-4 grid gap-3 text-sm md:grid-cols-2 lg:grid-cols-4">
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-500" />
            Executive Summary
          </div>
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-500" />
            {result.topIssues.length} Top Issues
          </div>
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-500" />
            {result.jiraTickets.length} Jira Tickets
          </div>
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-500" />
            Customer Communications
          </div>
        </div>
      </div>

      {/* Quick navigation */}
      <div className="flex items-center justify-between rounded-2xl border bg-muted/30 p-6">
        <div>
          <h3 className="font-semibold">All done!</h3>
          <p className="text-sm text-muted-foreground">
            Your analysis is complete. Export reports or return to Dashboard.
          </p>
        </div>
        <Link
          to="/dashboard"
          className="flex items-center gap-2 rounded-xl bg-primary px-5 py-2.5 font-medium text-primary-foreground transition-all hover:scale-[1.02]"
        >
          Back to Dashboard
          <ArrowRight size={16} />
        </Link>
      </div>
    </div>
  );
}
